export const supabaseUrl = "https://jdnjdbiflwgamipkjewd.supabase.co";
export const supabaseAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkbmpkYmlmbHdnYW1pcGtqZXdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjcwOTEwMzQsImV4cCI6MjA0MjY2NzAzNH0.swx3Pk_HvGNkSTeugWV1yrDDut2i7cy_W6VrwVyldME";
